[platformio]
src_dir = main
default_envs = xiao-arduino-rx

[env:xiao-arduino-rx]
platform = espressif32@7.0.1
platform_packages =
    platformio/framework-espidf@3.40407.240606
    platformio/framework-arduinoespressif32@3.20017.0
board = seeed_xiao_esp32s3
framework = arduino, espidf
monitor_speed = 115200
board_build.flash_size = 8MB
build_flags = -DARDUINO_USB_MODE=1 -DARDUINO_USB_CDC_ON_BOOT=1

[env:xiao-arduino-echo]
extends = env:xiao-arduino-rx
build_flags = ${env:xiao-arduino-rx.build_flags} -DLORA_SDR_ECHO_DEMO=1

[env:xiao-arduino-bench]
extends = env:xiao-arduino-rx
build_flags = ${env:xiao-arduino-rx.build_flags} -DLORA_SDR_SERIAL_BENCH=1

[env:xiao-arduino-ping]
extends = env:xiao-arduino-rx
build_flags = ${env:xiao-arduino-rx.build_flags} -DLORA_SDR_PING_DEMO=1

[env:xiao-arduino-pong]
extends = env:xiao-arduino-rx
build_flags = ${env:xiao-arduino-rx.build_flags} -DLORA_SDR_PONG_DEMO=1
