[env:aerolink-hf]
platform = espressif32@7.0.1
board = heltec_wifi_kit_32_V3
framework = arduino
lib_deps = jgromes/RadioLib@7.7.0
monitor_speed = 115200
build_flags =
    -DARDUINO_USB_CDC_ON_BOOT=1
    -DARDUINO_USB_MODE=1
