"""Generate native receiver coefficients; SciPy is a build-time tool only."""
from pathlib import Path
import numpy as np
from scipy.signal import butter, firwin

out=Path(__file__).resolve().parents[1]/'src'/'RxFilter.h'
sos=butter(10,203125/2,fs=250000,output='sos')
h=firwin(261,1/13,window=('kaiser',5.0))*13
def f(x): return f'{x:.10e}f'
out.write_text('// Generated by tools/generate_rx_filter.py. No runtime SciPy dependency.\n'
    '#pragma once\nnamespace lora_sdr {\nstatic const float rxSos[5][6] = {\n'
    +',\n'.join('    {'+', '.join(map(f,row))+'}' for row in sos)
    +'\n};\nstatic const float rxResample[261] = {\n'
    +',\n'.join('    '+', '.join(map(f,h[i:i+6])) for i in range(0,len(h),6))
    +'\n};\n}\n',encoding='utf-8')
